#!/bin/bash
set -e

# install clang-format if not exist (Ubuntu OS) 
which clang-format-15 1>/dev/null 2>&1
if [ $? -ne 0 ]; then
echo "install clang-format-15"
sudo apt install -y clang-format-15
fi

# clang-format each cpp file
for file in `git diff-index --cached --name-only HEAD | grep -iE "\.(cpp|cc|cxx|h|hpp)$"`; do
    echo $file
    clang-format-15 -i  $file --style=file
    git add $file
done

# 返回0以允许提交
exit 0

