name: Docker build and push

on:
  #  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
#    branches:
#      - workflow-work-2

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Add support for more platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/lite_tcp:latest
          annotations: |
            "org.opencontainers.image.title"="Lite Tcp Docker image"
            "org.opencontainers.image.description"="Lite Tcp multi-arch Docker image for development and test"
            "org.opencontainers.image.version"="0.1.0"
            "org.opencontainers.image.url"="https://github.com/truehang/lite_tcp"
