name: Docker build and push

on:
  workflow_dispatch:
  push:
#    paths:
#      - 'Dockerfile'
    branches:
      - workflow-work-2

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    # To config multi-arch
    strategy:
      matrix:
        platforms: 
          - name: linux/amd64
            tag: latest-amd64
          - name: linux/arm64
            tag: latest-arm64
          - name: linux/arm/v7
            tag: latest-armv7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Add support for more platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platforms.name }} 
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/lite_tcp:${{ matrix.platforms.tag }}
          annotations: |
            org.opencontainers.image.description=Lite Tcp multi-arch docker image for development and test
